version: '3.8'

services:

  db-final:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "2024"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 25s
      retries: 2

  db-source:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "2024"
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 25s
      retries: 2