{
 "title": "Monitoramento Sync-database",
 "description": "Teste de monitoramento do serviço Sync-database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sync-runnig",
   "type": "timeseries",
   "description": "Marcação de iniciação do sync-database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "service_running" }
   ]
  },
  {
   "title": "Tabela 1-dados_para_receber_testes",
   "type": "stat",
   "description": "Monitoramento de transferencia",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "read_count_total{job=\"sync-database\", table=\"1-dados_para_receber_testes\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "write_count_total{job=\"sync-database\", table=\"1-dados_para_receber_testes\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Execution time - 1-dados_para_receber_testes",
   "type": "stat",
   "description": "Tempo de execucao do servico na tabela de referencia",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time_count_total{job=\"sync-database\", table=\"1-dados_para_receber_testes\"}"
    }
   ]
  },
  {
   "title": "Tabela 2-recebimento_sem_ref",
   "type": "stat",
   "description": "Monitoramento de transferencia",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "read_count_total{job=\"sync-database\", table=\"2-recebimento_sem_ref\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "write_count_total{job=\"sync-database\", table=\"2-recebimento_sem_ref\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Execution time - 2-recebimento_sem_ref",
   "type": "stat",
   "description": "Tempo de execucao do servico na tabela de referencia",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time_count_total{job=\"sync-database\", table=\"2-recebimento_sem_ref\"}"
    }
   ]
  }
 ]
}