name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
env:
  VERSION: "3.10"

jobs:
  Code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: AutoModality/action-clean@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.VERSION }}
          cache: "pip"

      - name: Install dependencies     
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev gcc python3-dev
          python -m pip install --upgrade pip
          make init

      - name: Check Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check compilator
        if: always()
        run: |
            python3 -m compileall .

  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: AutoModality/action-clean@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.VERSION }}
          cache: "pip"

      - name: Install dependencies     
        run: |
          make install

      - name: Run tests
        run: echo "Nada ainda"
